version: 2

updates:
  # Back-End: Flask (Python)
  - package-ecosystem: "pip"
    directory: "/Deep-Learning"
    schedule:
      interval: "yearly" # Chỉ kiểm tra cập nhật 1 lần/năm
    ignore:
      - dependency-name: "*" # Bỏ qua tất cả các cập nhật

  # Front-End: Vue.js (npm hoặc yarn)
  - package-ecosystem: "npm"
    directory: "/Front-End"
    schedule:
      interval: "yearly" # Cập nhật rất ít để tránh bị làm phiền
    ignore:
      - dependency-name: "*" # Bỏ qua tất cả các cập nhật
